---
- name: Install msi package
  hosts: all
  tasks:
    - name: Task-1 - msi download
      win_get_url:
        url: https://archive.apache.org/dist/httpd/binaries/win32/httpd-2.2.25-win32-x86-no_ssl.msi
        dest: c:\ansibleproject\
        
    - name: Task 2 - Install msi pkg
      win_package:
        path: c:\ansibleproject\httpd-2.2.25-win32-x86-no_ssl.msi
        state: present
