---
- name: Uninstall an MSI package
  hosts: all
  tasks:
    - name: Uninstall task
      win_package:
        path: C:\ansibleproject\httpd-2.2.25-win32-x86-no_ssl.msi
        state: absent
    - name: remove package files 
      win_file:
        path: C:\ansibleproject\httpd-2.2.25-win32-x86-no_ssl.msi
